using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public interface LevelGenerator {

    /// <summary>
    /// Generates the map.
    /// </summary>
    /// <returns>A dictionary with the position of the tile as key and the tile as value.</returns>
    Dictionary<Vector3, Tile> Generate();

    /// <summary>
    /// Return the list of the tiles generated by the Generate function.
    /// </summary>
    /// <returns>List with the tiles.</returns>
    List<Vector3> GetTiles();
}
